service: officeverse-api

useDotenv: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  environment:
    DB_NAME: ${env:DB_NAME}
    DB_URL: ${env:DB_URL}
    FILE_UPLOAD_BUCKET_NAME: ${env:FILE_UPLOAD_BUCKET_NAME}
  httpApi:
    authorizers:
      cognitoJwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:AWS_REGION}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_CLIENT_ID_1}
          - ${env:COGNITO_CLIENT_ID_2}
          - ${env:COGNITO_CLIENT_ID_DEV}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-s3-local

package:
  exclude:
    - .env.stage
    - .env.prod
    - .env.local
  include:
    - .env.dev
  individually: true

functions:
  - ${file(./config/file-functions.yml)}
  - ${file(./config/challenges-functions.yml)}
  - ${file(./config/rewards-functions.yml)}
  - ${file(./config/users-functions.yml)}
# for local development, comment before deploying
# custom:
#   s3:
#     host: localhost
#     directory: /tmp

# resources:
#   Resources:
#     NewResource:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: local-bucket
