challengesCreate:
  handler: app/handler.challengesCreate
  events:
    - httpApi:
        method: POST
        path: /challenges
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: ${env:FILE_BUCKET_ARN}/*

challengesList:
  handler: app/handler.challengesList
  events:
    - httpApi:
        method: GET
        path: /challenges
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: ${env:FILE_BUCKET_ARN}/*
