rewardsCreate:
  handler: app/handler.rewardsCreate
  events:
    - httpApi:
        method: POST
        path: /rewards
        authorizer:
          name: cognitoJwtAuthorizer
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource: ${env:FILE_BUCKET_ARN}/*

rewardsList:
  handler: app/handler.rewardsList
  events:
    - httpApi:
        method: GET
        path: /rewards
        authorizer:
          name: cognitoJwtAuthorizer
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:GetObject'
      Resource: ${env:FILE_BUCKET_ARN}/*
