usersCreate:
  handler: app/handler.usersCreate
  events:
    - httpApi:
        method: POST
        path: /users
        authorizer:
          name: cognitoJwtAuthorizer

usersRetrieveProfile:
  handler: app/handler.usersRetrieveProfile
  events:
    - httpApi:
        method: GET
        path: /users/profile
        authorizer:
          name: cognitoJwtAuthorizer

usersRetrieveLeaderboards:
  handler: app/handler.usersRetrieveLeaderboards
  events:
    - httpApi:
        method: GET
        path: /users/leaderboards
        authorizer:
          name: cognitoJwtAuthorizer

usersResetWeeklyLeaderboards:
  handler: app/handler.usersResetWeeklyLeaderboards
  events:
    - schedule: cron(16 0 ? * MON *)

usersResetCode:
  handler: app/handler.usersResetCode
  events:
    - httpApi:
        method: POST
        path: /users/resetCode
        authorizer:
          name: cognitoJwtAuthorizer

usersUpdateCoins:
  handler: app/handler.usersUpdateCoins
  events:
    - httpApi:
        method: POST
        path: /users/{userId}/updateCoins
        authorizer:
          name: cognitoJwtAuthorizer

usersAddExp:
  handler: app/handler.usersAddExp
  events:
    - httpApi:
        method: POST
        path: /users/{userId}/addExp
        authorizer:
          name: cognitoJwtAuthorizer

usersUpdateAvatar:
  handler: app/handler.usersUpdateAvatar
  events:
    - httpApi:
        method: PATCH
        path: /users/{userId}/avatar
        authorizer:
          name: cognitoJwtAuthorizer

# read/write for custom:sign_up_code needs to be added manually
preSignUpValidateCode:
  handler: app/handler.preSignUpValidateCode
  events:
    - cognitoUserPool:
        pool: ${env:COGNITO_USER_POOL_NAME}
        trigger: PreSignUp
        existing: true
        forceDeploy: true
  environment:
    BYPASS_SIGN_UP_CODE: ${env:BYPASS_SIGN_UP_CODE}

onUserSignUpConfirmation:
  handler: app/handler.onUserSignUpConfirmation
  events:
    - cognitoUserPool:
        pool: ${env:COGNITO_USER_POOL_NAME}
        trigger: PostConfirmation
        existing: true
        forceDeploy: true
  environment:
    BYPASS_SIGN_UP_CODE: ${env:BYPASS_SIGN_UP_CODE}
